const SHOP_ACTION_TYPES = {
    FETCH_COLLECTIONS_START:"FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS:"FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTIONS_FAILED: "FETCH_COLLECTIONS_FAILED"
}

export default SHOP_ACTION_TYPES;
